Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "D:\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "D:\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "D:\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "D:\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "D:\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "D:\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# ----------- Estimated DAG based on NOTEARS 

mimic3_data_final = mimic3_data  

selected = ['Glucose', 'PaO2_FiO2', 'IV Input', 'SOFA', 'SOFA Post', 'Died within 48H']

sample_demo = mimic3_data_final[selected]
est_mt = notears_linear(np.array(sample_demo), lambda1=0, loss_type='l2',w_threshold=0.1)
 
# ----------- Refit Associated Matrix under LSEM 

est_mt, _ = refit(sample_demo, est_mt, selected) 
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mKeyError[0m                                  Traceback (most recent call last)
Input [1;32mIn [4][0m, in [0;36m<cell line: 7>[1;34m()[0m
[0;32m      3[0m mimic3_data_final [38;5;241m=[39m mimic3_data  
[0;32m      5[0m selected [38;5;241m=[39m [[38;5;124m'[39m[38;5;124mGlucose[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mPaO2_FiO2[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mIV Input[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mSOFA[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mSOFA Post[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mDied within 48H[39m[38;5;124m'[39m]
[1;32m----> 7[0m sample_demo [38;5;241m=[39m [43mmimic3_data_final[49m[43m[[49m[43mselected[49m[43m][49m
[0;32m      8[0m est_mt [38;5;241m=[39m notears_linear(np[38;5;241m.[39marray(sample_demo), lambda1[38;5;241m=[39m[38;5;241m0[39m, loss_type[38;5;241m=[39m[38;5;124m'[39m[38;5;124ml2[39m[38;5;124m'[39m,w_threshold[38;5;241m=[39m[38;5;241m0.1[39m)
[0;32m     10[0m [38;5;66;03m# ----------- Refit Associated Matrix under LSEM [39;00m

File [1;32mD:\anaconda3\lib\site-packages\pandas\core\frame.py:3511[0m, in [0;36mDataFrame.__getitem__[1;34m(self, key)[0m
[0;32m   3509[0m     [38;5;28;01mif[39;00m is_iterator(key):
[0;32m   3510[0m         key [38;5;241m=[39m [38;5;28mlist[39m(key)
[1;32m-> 3511[0m     indexer [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mcolumns[49m[38;5;241;43m.[39;49m[43m_get_indexer_strict[49m[43m([49m[43mkey[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mcolumns[39;49m[38;5;124;43m"[39;49m[43m)[49m[[38;5;241m1[39m]
[0;32m   3513[0m [38;5;66;03m# take() does not accept boolean indexers[39;00m
[0;32m   3514[0m [38;5;28;01mif[39;00m [38;5;28mgetattr[39m(indexer, [38;5;124m"[39m[38;5;124mdtype[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m) [38;5;241m==[39m [38;5;28mbool[39m:

File [1;32mD:\anaconda3\lib\site-packages\pandas\core\indexes\base.py:5782[0m, in [0;36mIndex._get_indexer_strict[1;34m(self, key, axis_name)[0m
[0;32m   5779[0m [38;5;28;01melse[39;00m:
[0;32m   5780[0m     keyarr, indexer, new_indexer [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_reindex_non_unique(keyarr)
[1;32m-> 5782[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_raise_if_missing[49m[43m([49m[43mkeyarr[49m[43m,[49m[43m [49m[43mindexer[49m[43m,[49m[43m [49m[43maxis_name[49m[43m)[49m
[0;32m   5784[0m keyarr [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mtake(indexer)
[0;32m   5785[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(key, Index):
[0;32m   5786[0m     [38;5;66;03m# GH 42790 - Preserve name from an Index[39;00m

File [1;32mD:\anaconda3\lib\site-packages\pandas\core\indexes\base.py:5845[0m, in [0;36mIndex._raise_if_missing[1;34m(self, key, indexer, axis_name)[0m
[0;32m   5842[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNone of [[39m[38;5;132;01m{[39;00mkey[38;5;132;01m}[39;00m[38;5;124m] are in the [[39m[38;5;132;01m{[39;00maxis_name[38;5;132;01m}[39;00m[38;5;124m][39m[38;5;124m"[39m)
[0;32m   5844[0m not_found [38;5;241m=[39m [38;5;28mlist[39m(ensure_index(key)[missing_mask[38;5;241m.[39mnonzero()[[38;5;241m0[39m]][38;5;241m.[39munique())
[1;32m-> 5845[0m [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mnot_found[38;5;132;01m}[39;00m[38;5;124m not in index[39m[38;5;124m"[39m)

[1;31mKeyError[0m: "['SOFA Post'] not in index"
KeyError: "['SOFA Post'] not in index"

